//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PchKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pchKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pchKhoa()
        {
            this.pchSinhViens = new HashSet<pchSinhVien>();
        }
    
        public string PchMaKH { get; set; }
        public string PchTenKH { get; set; }
        public Nullable<bool> PchTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pchSinhVien> pchSinhViens { get; set; }
    }
}
