//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PchKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pchSinhVien
    {
        public string PchMaSV { get; set; }
        public string PchHoSV { get; set; }
        public string PchTenSV { get; set; }
        public Nullable<System.DateTime> PchNgaySinh { get; set; }
        public Nullable<bool> PchPhai { get; set; }
        public string PchPhone { get; set; }
        public string PchEmail { get; set; }
        public string PchMaKH { get; set; }
    
        public virtual pchKhoa pchKhoa { get; set; }
    }
}
